(() => {
  'use strict';
  const PROFILE_KEY='wfgg-simulator-profile-v1',UI_KEY='wfgg-simulator-optimizer-ui-v1';
  const L={
    fr:{attack:'ATK affichée',defense:'DEF affichée',hp:'PV affichés',power:'Puissance affichée',monsterDamage:'Bonus dégâts monstres (%)',pveDamage:'Bonus dégâts PvE (%)',positionalBuff:'Buff positionnel PvE affiché (%)',attackHelp:'Ancre offensive pour les simulations.',defenseHelp:'Survie/placement contre les monstres uniquement.',hpHelp:'Survie/placement contre les monstres uniquement.',powerHelp:'Référence uniquement · jamais utilisée comme score direct.',monsterDamageHelp:'À saisir seulement si le bonus actuel est affiché ou vérifié.',pveDamageHelp:'Bonus PvE générique vérifié, si disponible.',positionalBuffHelp:'Utilisé seulement si le héros possède un effet positionnel audité (ex. Mason).',title:'Simulation PvE · Codes & monstres',codeText:'Code : dégâts offensifs sur 90 s. DEF, PV et puissance globale n’augmentent pas le score.',monsterText:'Monstres : le moteur protège d’abord la ligne avant puis maximise l’offensif. DEF et PV restent des diagnostics de survie séparés.',objective:'Objectif',team:'Équipe test',slot:'Héros',need5:'Ajoutez au moins 5 héros avec un nom pour lancer la simulation.',needAttack:'ATK affichée manquante pour :',needSurvival:'Pour la simulation monstres, renseignez aussi DEF et PV pour :',duplicate:'Chaque emplacement doit contenir un héros différent.',score:'Score offensif relatif',placements:'Placements valides / testés',positional:'Buffs positionnels',formation:'Bonus ATK formation',frontDefense:'Défenseurs devant',frontHp:'PV ligne avant',frontDef:'DEF ligne avant',codeRule:'Règle Codes',codeRuleText:'DEF = 0 · PV = 0 · Puissance globale = 0 dans le score offensif. Seuls les facteurs offensifs vérifiés classent les équipes.',monsterRule:'Règle Monstres',monsterRuleText:'Le monstre riposte : les héros Défense disponibles sont placés devant en priorité. ATK et survie ne sont jamais additionnées en une fausse puissance.',noEffects:'Aucun buff positionnel actif et vérifié pour ces cinq héros.',front:'Ligne avant',back:'Ligne arrière',researchCode:'Mode recherche · pas encore une prédiction exacte des dégâts 90 s.',researchMonster:'Mode recherche · classement offensif sous contrainte de survie, pas encore un temps de kill exact.',effects:'Effets de placement retenus',monsterOption:'Monstres PvE · générique'},
    en:{attack:'Displayed ATK',defense:'Displayed DEF',hp:'Displayed HP',power:'Displayed Power',monsterDamage:'Monster damage bonus (%)',pveDamage:'PvE damage bonus (%)',positionalBuff:'Displayed positional PvE buff (%)',attackHelp:'Offensive anchor for simulations.',defenseHelp:'Monster survival/placement only.',hpHelp:'Monster survival/placement only.',powerHelp:'Reference only · never used as a direct score.',monsterDamageHelp:'Enter only a displayed or verified current bonus.',pveDamageHelp:'Verified generic PvE bonus, when available.',positionalBuffHelp:'Used only for an audited positional effect (for example Mason).',title:'PvE simulation · Wanted & monsters',codeText:'Wanted: offensive output over 90 seconds. DEF, HP and displayed Power do not increase the score.',monsterText:'Monsters: protect the frontline first, then maximize offense. DEF and HP remain separate survival diagnostics.',objective:'Objective',team:'Test squad',slot:'Hero',need5:'Add at least 5 named heroes to run the simulation.',needAttack:'Missing displayed ATK for:',needSurvival:'For monster simulation also enter DEF and HP for:',duplicate:'Each slot must contain a different hero.',score:'Relative offense score',placements:'Eligible / tested placements',positional:'Positional buffs',formation:'Formation ATK bonus',frontDefense:'Defenders in front',frontHp:'Frontline HP',frontDef:'Frontline DEF',codeRule:'Wanted rule',codeRuleText:'DEF = 0 · HP = 0 · displayed Power = 0 in the offensive score. Only verified offensive factors rank squads.',monsterRule:'Monster rule',monsterRuleText:'The monster fights back: available Defense heroes are prioritized in front. ATK and survival are never added into fake Power.',noEffects:'No active verified positional buff for these five heroes.',front:'Front row',back:'Back row',researchCode:'Research mode · not yet an exact 90-second damage prediction.',researchMonster:'Research mode · offense ranking under a survival constraint, not yet an exact kill-time prediction.',effects:'Applied placement effects',monsterOption:'PvE monsters · generic'},
    it:{attack:'ATK mostrato',defense:'DIF mostrata',hp:'PS mostrati',power:'Potenza mostrata',monsterDamage:'Bonus danni ai mostri (%)',pveDamage:'Bonus danni PvE (%)',positionalBuff:'Buff PvE posizionale mostrato (%)',attackHelp:'Base offensiva per le simulazioni.',defenseHelp:'Solo sopravvivenza/posizione contro mostri.',hpHelp:'Solo sopravvivenza/posizione contro mostri.',powerHelp:'Solo riferimento · mai usata come punteggio diretto.',monsterDamageHelp:'Inserire solo un bonus attuale mostrato o verificato.',pveDamageHelp:'Bonus PvE generico verificato, se disponibile.',positionalBuffHelp:'Usato solo per un effetto posizionale verificato (es. Mason).',title:'Simulazione PvE · Wanted & mostri',codeText:'Wanted: rendimento offensivo in 90 s. DIF, PS e Potenza non aumentano il punteggio.',monsterText:'Mostri: prima protegge la prima linea, poi massimizza l’offesa. DIF e PS restano diagnostiche separate.',objective:'Obiettivo',team:'Squadra test',slot:'Eroe',need5:'Aggiungi almeno 5 eroi con nome.',needAttack:'ATK mostrato mancante per:',needSurvival:'Per i mostri inserisci anche DIF e PS per:',duplicate:'Ogni posizione deve contenere un eroe diverso.',score:'Punteggio offensivo relativo',placements:'Posizioni valide / testate',positional:'Buff posizionali',formation:'Bonus ATK formazione',frontDefense:'Difensori davanti',frontHp:'PS prima linea',frontDef:'DIF prima linea',codeRule:'Regola Wanted',codeRuleText:'DIF = 0 · PS = 0 · Potenza = 0 nel punteggio offensivo.',monsterRule:'Regola Mostri',monsterRuleText:'Il mostro contrattacca: gli eroi Difesa disponibili hanno priorità davanti. ATK e sopravvivenza non vengono sommate.',noEffects:'Nessun buff posizionale attivo e verificato per questi cinque eroi.',front:'Prima linea',back:'Seconda linea',researchCode:'Modalità ricerca · non ancora una previsione esatta dei danni in 90 s.',researchMonster:'Modalità ricerca · offesa sotto vincolo di sopravvivenza, non ancora tempo di uccisione esatto.',effects:'Effetti di posizione applicati',monsterOption:'Mostri PvE · generico'},
    es:{attack:'ATQ mostrado',defense:'DEF mostrada',hp:'PV mostrados',power:'Poder mostrado',monsterDamage:'Bonus daño a monstruos (%)',pveDamage:'Bonus daño PvE (%)',positionalBuff:'Buff PvE posicional mostrado (%)',attackHelp:'Base ofensiva para las simulaciones.',defenseHelp:'Solo supervivencia/posición contra monstruos.',hpHelp:'Solo supervivencia/posición contra monstruos.',powerHelp:'Solo referencia · nunca se usa como puntuación directa.',monsterDamageHelp:'Introduce solo un bonus actual mostrado o verificado.',pveDamageHelp:'Bonus PvE genérico verificado, si está disponible.',positionalBuffHelp:'Solo para un efecto posicional auditado (ej. Mason).',title:'Simulación PvE · Wanted y monstruos',codeText:'Wanted: rendimiento ofensivo durante 90 s. DEF, PV y Poder no aumentan la puntuación.',monsterText:'Monstruos: primero protege la línea delantera y después maximiza el ataque. DEF y PV quedan como diagnósticos separados.',objective:'Objetivo',team:'Escuadra de prueba',slot:'Héroe',need5:'Añade al menos 5 héroes con nombre.',needAttack:'Falta ATQ mostrado para:',needSurvival:'Para monstruos introduce también DEF y PV para:',duplicate:'Cada posición debe contener un héroe diferente.',score:'Puntuación ofensiva relativa',placements:'Posiciones válidas / probadas',positional:'Buffs posicionales',formation:'Bonus ATQ formación',frontDefense:'Defensores delante',frontHp:'PV línea delantera',frontDef:'DEF línea delantera',codeRule:'Regla Wanted',codeRuleText:'DEF = 0 · PV = 0 · Poder = 0 en la puntuación ofensiva.',monsterRule:'Regla Monstruos',monsterRuleText:'El monstruo contraataca: los héroes Defensa disponibles tienen prioridad delante. ATQ y supervivencia no se suman.',noEffects:'No hay buff posicional activo y verificado para estos cinco héroes.',front:'Línea delantera',back:'Línea trasera',researchCode:'Modo investigación · aún no es una predicción exacta de daño en 90 s.',researchMonster:'Modo investigación · ataque bajo restricción de supervivencia, aún no es tiempo de muerte exacto.',effects:'Efectos de posición aplicados',monsterOption:'Monstruos PvE · genérico'}
  };

  let formationSchema=null,rendering=false;
  const locale=()=>L[document.documentElement.lang]?document.documentElement.lang:'fr';
  const t=k=>L[locale()][k]||L.fr[k]||k;
  const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const profile=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY))||{};}catch(_){return {};}};
  const uiState=()=>{try{return Object.assign({objective:'wanted-39',heroes:[]},JSON.parse(localStorage.getItem(UI_KEY))||{});}catch(_){return{objective:'wanted-39',heroes:[]};}};
  const saveUi=s=>localStorage.setItem(UI_KEY,JSON.stringify(s));
  const isMonster=s=>s.objective==='monster-generic';
  async function loadFormation(){if(formationSchema)return formationSchema;formationSchema=await fetch('data/formation-positioning.v1.json').then(r=>{if(!r.ok)throw new Error('formation-positioning.v1.json');return r.json();});return formationSchema;}
  function setText(selector,value){document.querySelectorAll(selector).forEach(x=>{if(x.textContent!==value)x.textContent=value;});}
  function localizeFields(){['attack','defense','hp','power','monsterDamage','pveDamage','positionalBuff'].forEach(k=>{setText(`[data-opt-label="${k}"]`,t(k));setText(`[data-opt-help="${k}"]`,t(k+'Help'));});}
  function bestGrid(best){if(!best?.placement)return'';const p=best.placement,card=pos=>`<div class="formation-slot"><small>${esc(pos)}</small><strong>${esc(p[pos]?.heroId||'—')}</strong></div>`;return`<div class="formation-caption">${esc(t('front'))}</div><div class="formation-grid front">${card('front-left')}${card('front-right')}</div><div class="formation-caption">${esc(t('back'))}</div><div class="formation-grid back">${card('back-left')}${card('back-center')}${card('back-right')}</div>`;}
  function heroSelects(heroes,s){const ids=heroes.map(h=>h.heroId).filter(Boolean);if(s.heroes.length!==5||s.heroes.some(id=>!ids.includes(id)))s.heroes=ids.slice(0,5);while(s.heroes.length<5)s.heroes.push('');const options=value=>`<option value="">—</option>`+ids.map(id=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(id)}</option>`).join('');return`<div class="optimizer-select-grid">${s.heroes.map((id,i)=>`<label>${esc(t('slot'))} ${i+1}<select data-opt-hero="${i}">${options(id)}</select></label>`).join('')}</div>`;}
  function effectsHtml(applied){if(!applied.length)return'';return`<div class="optimizer-effect-list"><strong>${esc(t('effects'))}</strong>${applied.map(e=>`<span>${esc(e.providerHeroId)} → ${esc(e.targetHeroId)} · +${Number(e.value).toFixed(2)}% ${esc(e.stat)}</span>`).join('')}</div>`;}
  function ruleHtml(s){return`<div class="optimizer-rule"><strong>${esc(t(isMonster(s)?'monsterRule':'codeRule'))}</strong><span>${esc(t(isMonster(s)?'monsterRuleText':'codeRuleText'))}</span></div>`;}
  function introText(s){return t(isMonster(s)?'monsterText':'codeText');}
  function objectiveOptions(s){return`<option value="wanted-39" ${s.objective==='wanted-39'?'selected':''}>Code 39 · Aircraft +50%</option><option value="wanted-64" ${s.objective==='wanted-64'?'selected':''}>Code 64 · Missile +50%</option><option value="wanted-87" ${s.objective==='wanted-87'?'selected':''}>Code 87 · Tank +50%</option><option value="monster-generic" ${s.objective==='monster-generic'?'selected':''}>${esc(t('monsterOption'))}</option>`;}

  function renderResult(card,heroes,s,schema){
    const out=card.querySelector('#optimizerResult');if(!out)return;
    const chosen=s.heroes.map(id=>heroes.find(h=>h.heroId===id)).filter(Boolean);
    if(chosen.length!==5||new Set(s.heroes.map(x=>String(x).toLowerCase())).size!==5){out.innerHTML=`<div class="optimizer-message warning">${esc(t('duplicate'))}</div>`;return;}
    const missingAttack=chosen.filter(h=>!(Number(h.displayedAttack)>0)).map(h=>h.heroId);if(missingAttack.length){out.innerHTML=`<div class="optimizer-message warning">${esc(t('needAttack'))} <strong>${esc(missingAttack.join(', '))}</strong></div>`;return;}
    if(isMonster(s)){const missingSurvival=chosen.filter(h=>!(Number(h.displayedDefense)>0)||!(Number(h.displayedHp)>0)).map(h=>h.heroId);if(missingSurvival.length){out.innerHTML=`<div class="optimizer-message warning">${esc(t('needSurvival'))} <strong>${esc(missingSurvival.join(', '))}</strong></div>`;return;}}
    const engine=window.WfGgSimulatorEngine;if(!engine){out.innerHTML='<div class="optimizer-message warning">Engine indisponible.</div>';return;}
    try{
      const result=engine.optimizePlacement(chosen,s.objective,{heroEffects:schema.verifiedHeroEffects||[],geometry:schema.geometry||{},options:{verifiedOnly:true,includeUnverified:false}}),score=result.best.score;
      let metrics='';
      if(score.mode==='monster')metrics=`<div class="optimizer-metrics"><div><strong>${Math.round(score.relativeOffenseScore).toLocaleString()}</strong><small>${esc(t('score'))}</small></div><div><strong>${result.eligiblePlacements}/${result.evaluatedPlacements}</strong><small>${esc(t('placements'))}</small></div><div><strong>${score.frontDefenseRoleCount}/${score.requiredFrontDefenseCount}</strong><small>${esc(t('frontDefense'))}</small></div><div><strong>+${score.formationAttackPct}%</strong><small>${esc(t('formation'))}</small></div></div><div class="optimizer-survival-grid"><div><strong>${Math.round(score.frontlineHp).toLocaleString()}</strong><small>${esc(t('frontHp'))}</small></div><div><strong>${Math.round(score.frontlineDefense).toLocaleString()}</strong><small>${esc(t('frontDef'))}</small></div></div>`;
      else metrics=`<div class="optimizer-metrics"><div><strong>${Math.round(score.relativeOffenseScore).toLocaleString()}</strong><small>${esc(t('score'))}</small></div><div><strong>${result.evaluatedPlacements}/${result.fullPermutationSpace}</strong><small>${esc(t('placements'))}</small></div><div><strong>${score.appliedPositionalEffects.length}</strong><small>${esc(t('positional'))}</small></div><div><strong>+${score.formationAttackPct}%</strong><small>${esc(t('formation'))}</small></div></div>`;
      out.innerHTML=metrics+bestGrid(result.best)+effectsHtml(score.appliedPositionalEffects)+(result.positionalOptimizationActive?'':`<div class="optimizer-message info">${esc(t('noEffects'))}</div>`)+`<p class="fine-print">${esc(t(score.mode==='monster'?'researchMonster':'researchCode'))}</p>`;
    }catch(err){out.innerHTML=`<div class="optimizer-message warning">${esc(err.message)}</div>`;}
  }

  async function renderCard(){
    if(rendering)return;const host=document.querySelector('#step-summary');if(!host||host.querySelector('#codeOptimizerCard'))return;rendering=true;
    try{
      const schema=await loadFormation(),p=profile(),heroes=(p.heroes||[]).filter(h=>h.heroId),s=uiState(),card=document.createElement('section');card.id='codeOptimizerCard';card.className='section-card optimizer-card';
      let body=`<div class="optimizer-head"><div><p class="eyebrow">WfGg Engine</p><h3>${esc(t('title'))}</h3><p id="optimizerIntro" class="muted">${esc(introText(s))}</p></div><span class="status-pill">v1.2</span></div><div id="optimizerRule">${ruleHtml(s)}</div>`;
      if(heroes.length<5){card.innerHTML=body+`<div class="optimizer-message">${esc(t('need5'))}</div>`;host.prepend(card);return;}
      body+=`<div class="optimizer-controls"><label>${esc(t('objective'))}<select id="codeObjective">${objectiveOptions(s)}</select></label></div><h4>${esc(t('team'))}</h4>${heroSelects(heroes,s)}<div id="optimizerResult"></div>`;card.innerHTML=body;host.prepend(card);saveUi(s);
      card.querySelector('#codeObjective').onchange=e=>{s.objective=e.target.value;saveUi(s);card.querySelector('#optimizerIntro').textContent=introText(s);card.querySelector('#optimizerRule').innerHTML=ruleHtml(s);renderResult(card,heroes,s,schema);};
      card.querySelectorAll('[data-opt-hero]').forEach(sel=>sel.onchange=e=>{s.heroes[Number(e.target.dataset.optHero)]=e.target.value;saveUi(s);renderResult(card,heroes,s,schema);});renderResult(card,heroes,s,schema);
    }catch(err){console.error(err);}finally{rendering=false;localizeFields();}
  }
  function tick(){localizeFields();renderCard();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{tick();setInterval(tick,600);});else{tick();setInterval(tick,600);}
})();
