/* WfGg Portal admin enhancements v0.4.1 */
window.WFGG_LEGACY_AVATARS = Object.freeze({
  "Metatouk": "https://wfgg-train-app.pages.dev/assets/avatars/p001-metatouk.jpg",
  "Ogie Ogilthorpe 7": "https://wfgg-train-app.pages.dev/assets/avatars/p007-ogie-ogilthorpe-7.jpg",
  "ValFada": "https://wfgg-train-app.pages.dev/assets/avatars/p004-valfada.jpg",
  "Shockwave XY": "https://wfgg-train-app.pages.dev/assets/avatars/p010-shockwave-xy.jpg",
  "Le Ced83": "https://wfgg-train-app.pages.dev/assets/avatars/p005-le-ced83.jpg",
  "Sab93fr": "https://wfgg-train-app.pages.dev/assets/avatars/p009-sab93fr.jpg",
  "SnooPsy": "https://wfgg-train-app.pages.dev/assets/avatars/p011-snoopsy.jpg",
  "El Tonton": "https://wfgg-train-app.pages.dev/assets/avatars/p002-el-tonton.jpg",
  "εlα ツ": "https://wfgg-train-app.pages.dev/assets/avatars/p008-player.jpg",
  "cat 49": "https://wfgg-train-app.pages.dev/assets/avatars/p003-cat-49.jpg",
  "Flawene": "https://wfgg-train-app.pages.dev/assets/avatars/p006-flawene.jpg",
  "Olma92": "https://wfgg-train-app.pages.dev/assets/avatars/p012-olma92.jpg",
  "tacatacafacatac": "https://wfgg-train-app.pages.dev/assets/avatars/p013-tacatacatacatacatac.jpg",
  "Momolapéro": "https://wfgg-train-app.pages.dev/assets/avatars/p034-momolap-ro.jpg",
  "le vrai loulou": "https://wfgg-train-app.pages.dev/assets/avatars/p026-le-vrai-loulou.jpg",
  "The Clock": "https://wfgg-train-app.pages.dev/assets/avatars/p039-the-clock.jpg",
  "εlσ": "https://wfgg-train-app.pages.dev/assets/avatars/p052-player.jpg",
  "pirate 77": "https://wfgg-train-app.pages.dev/assets/avatars/p032-pirate-77.jpg",
  "lesmignon": "https://wfgg-train-app.pages.dev/assets/avatars/p053-lesmignon.jpg",
  "MatBoy": "https://wfgg-train-app.pages.dev/assets/avatars/p021-matboy.jpg",
  "Bidibidobidiboo": "https://wfgg-train-app.pages.dev/assets/avatars/p048-ridihidibidibou.jpg",
  "Blackbeard 44": "https://wfgg-train-app.pages.dev/assets/avatars/p054-blackbeard-44.jpg",
  "barbiche974": "https://wfgg-train-app.pages.dev/assets/avatars/p037-barbiche974.jpg",
  "Kenny Swiss": "https://wfgg-train-app.pages.dev/assets/avatars/p060-kenny-swiss.jpg",
  "I AM THE DANGER": "https://wfgg-train-app.pages.dev/assets/avatars/p046-i-am-the-danger.jpg",
  "zazavibes": "https://wfgg-train-app.pages.dev/assets/avatars/p022-zazavibes.jpg",
  "Karissma84": "https://wfgg-train-app.pages.dev/assets/avatars/p065-karissma84.jpg",
  "LeBriviste": "https://wfgg-train-app.pages.dev/assets/avatars/p028-lebriviste.jpg",
  "PopOTal": "https://wfgg-train-app.pages.dev/assets/avatars/p038-pop0tal.jpg",
  "tomek20": "https://wfgg-train-app.pages.dev/assets/avatars/p050-tomek20.jpg",
  "Ghis123": "https://wfgg-train-app.pages.dev/assets/avatars/p041-ghis123.jpg",
  "OzMasta": "https://wfgg-train-app.pages.dev/assets/avatars/p019-ozmasta.jpg",
  "Albeddo": "https://wfgg-train-app.pages.dev/assets/avatars/p045-albeddo.jpg",
  "K4ruto": "https://wfgg-train-app.pages.dev/assets/avatars/p030-k4ruto.jpg",
  "Cde Mitchel": "https://wfgg-train-app.pages.dev/assets/avatars/p024-cde-mitchel.jpg",
  "butrfly": "https://wfgg-train-app.pages.dev/assets/avatars/p059-hurfly.jpg",
  "Mataac": "https://wfgg-train-app.pages.dev/assets/avatars/p029-mataac.jpg",
  "Clapotutu": "https://wfgg-train-app.pages.dev/assets/avatars/p031-clapotutu.jpg",
  "Extrakt": "https://wfgg-train-app.pages.dev/assets/avatars/p044-extraky.jpg",
  "NemezisOff": "https://wfgg-train-app.pages.dev/assets/avatars/p061-nemezisoff.jpg",
  "Letoll 71": "https://wfgg-train-app.pages.dev/assets/avatars/p051-letoll-71.jpg",
  "loubart": "https://wfgg-train-app.pages.dev/assets/avatars/p049-loubart.jpg",
  "Dieu Freud": "https://wfgg-train-app.pages.dev/assets/avatars/p035-dieu-freud.jpg",
  "Silkan": "https://wfgg-train-app.pages.dev/assets/avatars/p014-silkan.jpg",
  "jadou09": "https://wfgg-train-app.pages.dev/assets/avatars/p062-jadou09.jpg",
  "micky6": "https://wfgg-train-app.pages.dev/assets/avatars/p018-micky6.jpg",
  "FredMol34": "https://wfgg-train-app.pages.dev/assets/avatars/p043-fredmol34.jpg",
  "lufna": "https://wfgg-train-app.pages.dev/assets/avatars/p040-lufna.jpg",
  "Koburo to Harokku": "https://wfgg-train-app.pages.dev/assets/avatars/p033-koburo-to-harakku.jpg",
  "ZeBatman": "https://wfgg-train-app.pages.dev/assets/avatars/p056-zebatman.jpg",
  "Alaa Shaheen1977": "https://wfgg-train-app.pages.dev/assets/avatars/p042-alaa-shaheen1977.jpg",
  "XSeiyaX": "https://wfgg-train-app.pages.dev/assets/avatars/p015-xseiyax.jpg",
  "David 18410": "https://wfgg-train-app.pages.dev/assets/avatars/p016-david-18410.jpg",
  "Holy Kitty": "https://wfgg-train-app.pages.dev/assets/avatars/p025-holy-kitty.jpg",
  "Jeremysterieux": "https://wfgg-train-app.pages.dev/assets/avatars/p057-jeremysterieux.jpg",
  "GSF7": "https://wfgg-train-app.pages.dev/assets/avatars/p017-gsf7.jpg",
  "masayoshi8": "https://wfgg-train-app.pages.dev/assets/avatars/p058-masayoshi8.jpg",
  "pepelcox": "https://wfgg-train-app.pages.dev/assets/avatars/p095-pepeclax.jpg",
  "LE VEILLEUR 62": "https://wfgg-train-app.pages.dev/assets/avatars/p063-le-veilleur-62.jpg",
  "Lilith 0666": "https://wfgg-train-app.pages.dev/assets/avatars/p093-lilith-0666.jpg",
  "Manu P": "https://wfgg-train-app.pages.dev/assets/avatars/p070-manu-t.jpg",
  "Warzazat 38": "https://wfgg-train-app.pages.dev/assets/avatars/p073-warrazat-38.jpg",
  "Pandableu": "https://wfgg-train-app.pages.dev/assets/avatars/p077-pandalieu.jpg",
  "Carameloo": "https://wfgg-train-app.pages.dev/assets/avatars/p090-caramelino.jpg",
  "koty93700": "https://wfgg-train-app.pages.dev/assets/avatars/p085-kntg93700.jpg",
  "Pika31": "https://wfgg-train-app.pages.dev/assets/avatars/p069-pika31.jpg",
  "DWADZ": "https://wfgg-train-app.pages.dev/assets/avatars/p075-dwadz.jpg",
  "Estafar": "https://wfgg-train-app.pages.dev/assets/avatars/p071-estafar.jpg",
  "BoskaOne": "https://wfgg-train-app.pages.dev/assets/avatars/p067-floskaone.jpg",
  "azdi2307": "https://wfgg-train-app.pages.dev/assets/avatars/p083-axdi2307.jpg",
  "JC 211": "https://wfgg-train-app.pages.dev/assets/avatars/p080-jc-211.jpg",
  "PereBlaise": "https://wfgg-train-app.pages.dev/assets/avatars/p081-pereblaise.jpg",
  "mariolagrem": "https://wfgg-train-app.pages.dev/assets/avatars/p088-marinlagrem.jpg",
  "HavanaBlackCat": "https://wfgg-train-app.pages.dev/assets/avatars/p096-havanablackcat.jpg",
  "Stefdu95": "https://wfgg-train-app.pages.dev/assets/avatars/p086-stefdu95.jpg",
  "HAWEWE": "https://wfgg-train-app.pages.dev/assets/avatars/p084-hawewe.jpg",
  "socosmic": "https://wfgg-train-app.pages.dev/assets/avatars/p087-sacosmic.jpg",
  "5Teste": "https://wfgg-train-app.pages.dev/assets/avatars/p092-steste.jpg",
  "Mat Matalo": "https://wfgg-train-app.pages.dev/assets/avatars/p036-mat-matalo.jpg",
  "Placide74": "https://wfgg-train-app.pages.dev/assets/avatars/p079-plucide74.jpg",
  "Sébich": "https://wfgg-train-app.pages.dev/assets/avatars/p074-sebich.jpg",
  "mike1964": "https://wfgg-train-app.pages.dev/assets/avatars/p078-mike1954.jpg",
  "Qlulu": "https://wfgg-train-app.pages.dev/assets/avatars/p047-qlulu.jpg",
  "Malarkey14": "https://wfgg-train-app.pages.dev/assets/avatars/p020-malarkey14.jpg",
  "gode of war": "https://wfgg-train-app.pages.dev/assets/avatars/p064-gode-of-war.jpg",
  "fredspdl": "https://wfgg-train-app.pages.dev/assets/avatars/p091-fredspd.jpg",
  "AieRon MAN": "https://wfgg-train-app.pages.dev/assets/avatars/p072-aieron-man.jpg",
  "Atzia": "https://wfgg-train-app.pages.dev/assets/avatars/p076-arzia.jpg",
  "Nishy FR": "https://wfgg-train-app.pages.dev/assets/avatars/p094-nishy-fr.jpg",
  "Copsyco": "https://wfgg-train-app.pages.dev/assets/avatars/p066-copsync.jpg"
});
