(() => {
'use strict';
const cfg=window.WFGG_PORTAL_CONFIG||{API_BASE:'',MODULES:{}};
const LEGACY=window.WFGG_LEGACY_AVATARS||{};
const TOKEN_KEY='wfgg_portal_session', LANG_KEY='wfgg_portal_language';
const RANKS=['R5','R4','R3','R2','R1'];
const OFFICES=['','WARLORD','RECRUITER','MUSE','BUTLER'];
const OFFICE_FR={WARLORD:'Seigneur de guerre',RECRUITER:'Recruteur',MUSE:'Muse',BUTLER:'Majordome'};
const state={user:null,membership:null,alliance:null,system:null,permissions:null,portalSettings:{},lang:localStorage.getItem(LANG_KEY)||'fr',members:[],filters:new Set(),search:'',settingsTab:'profile',sessions:[]};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18N={
 fr:{auth:{title:'Portail',subtitle:'Entrez votre code WfGg pour vous connecter.',code:'Code d’authentification',login:'Se connecter',bad:'Code invalide ou compte désactivé.'},home:{portal:'Portail',welcome:'Bienvenue',settings:'⚙️ Paramètres',logout:'Déconnexion',profileIncomplete:'Votre profil est incomplet. Vous pouvez le compléter dans Paramètres.',guidesSub:'Saison 6 et Inter-Saison',trainSub:'Organisation et rotations',settingsSub:'Profil, alliance et administration'},settings:{title:'Paramètres',profile:'Mon profil',alliance:'Alliance',application:'Application',rights:'Droits & accès',save:'Enregistrer',security:'Sécurité de mon profil',sessions:'Mes sessions'},members:{title:'Joueurs de l’alliance',add:'Ajouter un joueur',search:'Rechercher un pseudo…',edit:'Modifier',disable:'Désactiver',enable:'Réactiver'}},
 it:{auth:{title:'Portale',subtitle:'Inserisci il tuo codice WfGg per accedere.',code:'Codice di autenticazione',login:'Accedi',bad:'Codice non valido o account disattivato.'},home:{portal:'Portale',welcome:'Benvenuto',settings:'⚙️ Impostazioni',logout:'Disconnetti',profileIncomplete:'Il tuo profilo è incompleto. Puoi completarlo nelle Impostazioni.',guidesSub:'Stagione 6 e Interstagione',trainSub:'Organizzazione e rotazioni',settingsSub:'Profilo, alleanza e amministrazione'},settings:{title:'Impostazioni',profile:'Il mio profilo',alliance:'Alleanza',application:'Applicazione',rights:'Diritti e accesso',save:'Salva',security:'Sicurezza del mio profilo',sessions:'Le mie sessioni'},members:{title:'Giocatori dell’alleanza',add:'Aggiungi giocatore',search:'Cerca un nome…',edit:'Modifica',disable:'Disattiva',enable:'Riattiva'}},
 en:{auth:{title:'Portal',subtitle:'Enter your WfGg code to sign in.',code:'Authentication code',login:'Sign in',bad:'Invalid code or disabled account.'},home:{portal:'Portal',welcome:'Welcome',settings:'⚙️ Settings',logout:'Sign out',profileIncomplete:'Your profile is incomplete. You can complete it in Settings.',guidesSub:'Season 6 and Interseason',trainSub:'Organisation and rotations',settingsSub:'Profile, alliance and administration'},settings:{title:'Settings',profile:'My profile',alliance:'Alliance',application:'Application',rights:'Rights & access',save:'Save',security:'My profile security',sessions:'My sessions'},members:{title:'Alliance players',add:'Add player',search:'Search a player…',edit:'Edit',disable:'Disable',enable:'Enable'}},
 es:{auth:{title:'Portal',subtitle:'Introduce tu código WfGg para iniciar sesión.',code:'Código de autenticación',login:'Entrar',bad:'Código no válido o cuenta desactivada.'},home:{portal:'Portal',welcome:'Bienvenido',settings:'⚙️ Ajustes',logout:'Cerrar sesión',profileIncomplete:'Tu perfil está incompleto. Puedes completarlo en Ajustes.',guidesSub:'Temporada 6 e Intertemporada',trainSub:'Organización y rotaciones',settingsSub:'Perfil, alianza y administración'},settings:{title:'Ajustes',profile:'Mi perfil',alliance:'Alianza',application:'Aplicación',rights:'Derechos y acceso',save:'Guardar',security:'Seguridad de mi perfil',sessions:'Mis sesiones'},members:{title:'Jugadores de la alianza',add:'Añadir jugador',search:'Buscar jugador…',edit:'Editar',disable:'Desactivar',enable:'Reactivar'}}
};
const t=path=>path.split('.').reduce((o,k)=>o?.[k],I18N[state.lang]||I18N.fr)||path;
const isAdmin=()=>Boolean(state.permissions?.can_admin_members && ['R4','R5'].includes(state.membership?.rank));
const profileComplete=()=>Boolean(state.user?.profile_completed);
function setView(id){['bootView','authView','portalView'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden')}
function token(){return localStorage.getItem(TOKEN_KEY)}
async function api(path,options={}){const h=new Headers(options.headers||{});if(token())h.set('Authorization',`Bearer ${token()}`);if(options.body&&!(options.body instanceof FormData)&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(`${cfg.API_BASE}${path}`,{...options,headers:h,cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(r.status===401){clearSession();showAuth();throw new Error('UNAUTHORIZED')}if(!r.ok)throw new Error(d?.error||`HTTP_${r.status}`);return d}
function clearSession(){localStorage.removeItem(TOKEN_KEY);Object.assign(state,{user:null,membership:null,alliance:null,system:null,permissions:null,portalSettings:{},members:[],sessions:[]});}
function initials(n='?'){return n.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'?'}
function avatarUrl(u){return u?.avatar_url||LEGACY[u?.player_name]||LEGACY[u?.display_name]||''}
function paintAvatar(el,u){if(!el||!u)return;const src=avatarUrl(u);el.innerHTML=src?`<img src="${esc(src)}" alt="${esc(u.display_name||u.player_name||'joueur')}">`:esc(initials(u.display_name||u.player_name))}
function applyLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));renderHome();}
function hydrate(d){state.user=d.user;state.membership=d.membership;state.alliance=d.alliance;state.system=d.system||{};state.permissions=d.permissions||{};state.portalSettings=d.portal_settings||{};if(d.user?.language&&I18N[d.user.language]){state.lang=d.user.language;localStorage.setItem(LANG_KEY,state.lang)}applyLanguage();}
function showAuth(){setView('authView');setTimeout(()=>$('authCode')?.focus(),30)}
function showPortal(){setView('portalView');renderHome();}
const DEFAULT_ALLIANCE_LOGO='https://wfgg-train-app.pages.dev/assets/icon-192.png';
function setAllianceLogo(imgId,fallbackId){
  const img=$(imgId),fallback=$(fallbackId);
  if(!img||!fallback)return;
  const src=state.alliance?.logo_url||DEFAULT_ALLIANCE_LOGO;
  fallback.classList.remove('hidden');
  img.classList.add('hidden');
  if(!src)return;
  img.onload=()=>{img.classList.remove('hidden');fallback.classList.add('hidden')};
  img.onerror=()=>{img.classList.add('hidden');fallback.classList.remove('hidden')};
  img.src=src;
}
function paintAllianceIdentity(){
  const allianceName=state.alliance?.name||'WfGg';
  const server=state.alliance?.server||'—';
  if($('topAllianceName'))$('topAllianceName').textContent=allianceName;
  if($('topAllianceMeta'))$('topAllianceMeta').textContent='Alliance · Serveur '+server;
  if($('heroAllianceName'))$('heroAllianceName').textContent=allianceName;
  if($('heroAllianceServer'))$('heroAllianceServer').textContent='Serveur '+server;
  setAllianceLogo('topAllianceLogo','topAllianceFallback');
  setAllianceLogo('heroAllianceLogo','heroAllianceFallback');
}
function renderHome(){if(!state.user)return;paintAllianceIdentity();const name=state.user.display_name||state.user.player_name;$('topName').textContent=name;$('heroName').textContent=name;$('topRole').textContent=state.membership?.rank||'—';paintAvatar($('topAvatar'),state.user);$('profileRequiredBanner').classList.toggle('hidden',profileComplete());$('homeWelcome').textContent=state.portalSettings?.welcome_text||t('home.settingsSub').replace('Profil, alliance et administration','Choisissez votre espace WfGg.').replace('Profile, alliance and administration','Choose your WfGg space.').replace('Profilo, alleanza e amministrazione','Scegli il tuo spazio WfGg.').replace('Perfil, alianza y administración','Elige tu espacio WfGg.');$('guidesCardTitle').textContent=state.portalSettings?.guides_title||'Guides';$('trainCardTitle').textContent=state.portalSettings?.train_title||'Train';}
function moduleUrl(k){const stored=state.portalSettings?.[`${k}_url`];return stored||cfg.MODULES?.[k]||''}
function openModule(k){const u=moduleUrl(k);if(u)location.href=u}
function showMessage(id,text,error=false){const el=$(id);if(!el)return;el.textContent=text;el.className=`form-message${error?' error':''}`;setTimeout(()=>el.classList.add('hidden'),3500)}
async function boot(){applyLanguage();if(!token())return showAuth();try{hydrate(await api('/api/me'));showPortal()}catch(e){if(e.message!=='UNAUTHORIZED')showAuth()}}

// auth + main navigation
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').classList.add('hidden');try{const d=await api('/api/auth',{method:'POST',body:JSON.stringify({code:$('authCode').value.trim()})});localStorage.setItem(TOKEN_KEY,d.session_token);hydrate(d);$('authCode').value='';showPortal()}catch{$('authError').textContent=t('auth.bad');$('authError').classList.remove('hidden')}});
$('languageStrip').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;state.lang=b.dataset.lang;localStorage.setItem(LANG_KEY,state.lang);applyLanguage()});
$('profileChip').addEventListener('click',()=>{$('profileMenu').classList.toggle('hidden')});
$('homeButton').addEventListener('click',()=>{showPortal();scrollTo({top:0,behavior:'smooth'})});
document.addEventListener('click',async e=>{const module=e.target.closest('[data-module]');if(module)return openModule(module.dataset.module);const a=e.target.closest('[data-action]');if(!a)return;const x=a.dataset.action;if(x==='settings')return openSettings('profile');if(x==='logout'){try{await api('/api/logout',{method:'POST'})}catch{}clearSession();$('settingsOverlay').classList.add('hidden');$('membersView').classList.add('hidden');showAuth();return}if(x==='close-settings')return closeSettings();if(x==='close-members')return closeMembers();if(x==='add-member')return openMemberModal();if(x==='edit-member')return openMemberModal(a.dataset.id);if(x==='toggle-member')return toggleMember(a.dataset.id);if(x==='close-modal')return closeModal();if(x==='save-member')return saveMember();if(x==='reset-member-code')return resetMemberCode(a.dataset.id);if(x==='transfer-r5')return openTransfer(a.dataset.id);if(x==='confirm-transfer')return confirmTransfer(a.dataset.id);if(x==='copy-code')return copyText(a.dataset.code,a);if(x==='revoke-others')return revokeOthers();});

// settings
const tabDefs=()=>[{id:'profile',label:t('settings.profile')},...(isAdmin()?[{id:'alliance',label:t('settings.alliance')},{id:'application',label:t('settings.application')},{id:'rights',label:t('settings.rights')}]:[])];
function openSettings(tab='profile'){$('profileMenu').classList.add('hidden');state.settingsTab=isAdmin()||tab==='profile'?tab:'profile';$('settingsOverlay').classList.remove('hidden');renderSettings()}
function closeSettings(){$('settingsOverlay').classList.add('hidden')}
function renderSettings(){const tabs=$('settingsTabs');tabs.innerHTML=tabDefs().map(x=>`<button class="tab ${state.settingsTab===x.id?'active':''}" type="button" data-settings-tab="${x.id}">${esc(x.label)}</button>`).join('');renderSettingsContent()}
$('settingsTabs').addEventListener('click',e=>{const b=e.target.closest('[data-settings-tab]');if(!b)return;const id=b.dataset.settingsTab;if(id!=='profile'&&!isAdmin())return;state.settingsTab=id;renderSettings()});
function readonly(){return `<div class="readonly-grid"><div><small>Alliance</small><strong>${esc(state.alliance?.name||'—')}</strong></div><div><small>Serveur</small><strong>${esc(state.alliance?.server||'—')}</strong></div><div><small>Rang</small><strong>${esc(state.membership?.rank||'—')}</strong></div></div>`}
function renderSettingsContent(){const c=$('settingsContent');if(state.settingsTab==='profile')c.innerHTML=profileSettingsHtml();else if(state.settingsTab==='alliance'&&isAdmin())c.innerHTML=allianceSettingsHtml();else if(state.settingsTab==='application'&&isAdmin())c.innerHTML=applicationSettingsHtml();else if(state.settingsTab==='rights'&&isAdmin())c.innerHTML=rightsHtml();else{state.settingsTab='profile';c.innerHTML=profileSettingsHtml()}bindSettingsForms();}
function profileSettingsHtml(){const name=state.user?.display_name||state.user?.player_name||'';return `<div class="settings-section"><form id="profileForm" class="settings-form"><div class="settings-card-block"><div class="avatar-editor"><span id="settingsAvatar" class="avatar large"></span><div><label class="secondary-button file-button">📷 Changer la photo<input id="avatarInput" class="hidden" type="file" accept="image/jpeg,image/png,image/webp"></label><small class="muted">JPG, PNG ou WebP · 2 Mo max · carré 1:1</small></div></div><label class="field-label">Pseudo affiché</label><input id="displayName" maxlength="40" value="${esc(name)}"><label class="field-label">Langue</label><select id="languageSelect"><option value="fr">Français</option><option value="it">Italiano</option><option value="en">English</option><option value="es">Español</option></select>${readonly()}<button class="primary-button" type="submit">${esc(t('settings.save'))}</button><div id="profileMessage" class="hidden"></div></div></form><div class="settings-card-block"><h3>🔐 ${esc(t('settings.security'))}</h3><form id="codeForm" class="settings-form"><label class="field-label">Code actuel</label><input id="currentCode" type="password" inputmode="numeric" maxlength="6" placeholder="••••••"><label class="field-label">Nouveau code</label><input id="newCode" type="password" inputmode="numeric" maxlength="6" placeholder="••••••"><button class="secondary-button" type="submit">Changer mon code</button><div id="codeMessage" class="hidden"></div></form><div class="section-heading" style="margin-top:16px"><h3>${esc(t('settings.sessions'))}</h3><button id="refreshSessions" class="secondary-button" type="button">Actualiser</button></div><div id="sessionList" class="session-list"><span class="muted">Chargement…</span></div><div class="setting-actions"><button class="secondary-button" type="button" data-action="revoke-others">Fermer les autres sessions</button></div></div></div>`}
function allianceSettingsHtml(){return `<div class="settings-section"><form id="allianceForm" class="settings-form"><div class="settings-card-block"><h3>🏰 Alliance</h3><label class="field-label">Nom</label><input id="allianceName" maxlength="50" value="${esc(state.alliance?.name||'')}"><label class="field-label">Serveur</label><input id="allianceServer" maxlength="30" value="${esc(state.alliance?.server||'')}"><label class="field-label">Logo (URL)</label><input id="allianceLogo" maxlength="500" value="${esc(state.alliance?.logo_url||'')}"><button class="primary-button" type="submit">${esc(t('settings.save'))}</button><div id="allianceMessage" class="hidden"></div></div></form><div class="settings-card-block"><div class="section-heading"><div><h3>👥 Membres</h3><p class="muted">Rangs, fonctions R4, codes, activation et R5.</p></div><button id="openMembersButton" class="primary-button" type="button">Gérer les membres</button></div></div></div>`}
function applicationSettingsHtml(){const p=state.portalSettings||{};return `<form id="applicationForm" class="settings-form"><div class="settings-card-block"><h3>✨ Application</h3><p class="muted">Réglages généraux du portail. Les paramètres de rotation restent dans Train.</p><label class="field-label">Texte d’accueil</label><textarea id="welcomeText" maxlength="180" rows="3">${esc(p.welcome_text||'Choisissez votre espace WfGg.')}</textarea><label class="field-label">Titre Guides</label><input id="guidesTitle" maxlength="40" value="${esc(p.guides_title||'Guides')}"><label class="field-label">URL Guides</label><input id="guidesUrl" maxlength="500" value="${esc(p.guides_url||cfg.MODULES?.guides||'')}"><label class="field-label">Titre Train</label><input id="trainTitle" maxlength="40" value="${esc(p.train_title||'Train')}"><label class="field-label">URL Train</label><input id="trainUrl" maxlength="500" value="${esc(p.train_url||cfg.MODULES?.train||'')}"><button class="primary-button" type="submit">${esc(t('settings.save'))}</button><div id="applicationMessage" class="hidden"></div></div></form>`}
function rightsHtml(){const rank=state.membership?.rank||'—',owner=state.system?.role==='OWNER';return `<div class="settings-section"><div class="settings-card-block"><h3>🛡️ Politique des droits</h3><p class="muted">Les droits sont calculés côté API à chaque requête. Un changement de rang invalide la session du joueur concerné.</p><div class="permission-grid"><div class="permission-row"><b>Fonction</b><strong>R4/R5</strong><strong>R1–R3</strong></div>${['Profil personnel','Paramètres généraux','Alliance & membres','Gestion des rangs','Fonctions R4','Changer le R5','Administration'].map((x,i)=>`<div class="permission-row"><span>${x}</span><strong class="ok">✓</strong><strong class="${i===0?'ok':'no'}">${i===0?'✓':'—'}</strong></div>`).join('')}</div></div><div class="settings-card-block"><h3>Ton accès</h3><p>Rang : <strong>${esc(rank)}</strong>${state.membership?.officer_title?` · ${esc(OFFICE_FR[state.membership.officer_title]||state.membership.officer_title)}`:''}${owner?' · <strong>OWNER</strong>':''}</p><p class="muted">OWNER est un rôle système séparé du rang de jeu et reste protégé.</p></div></div>`}
function bindSettingsForms(){paintAvatar($('settingsAvatar'),state.user);if($('languageSelect'))$('languageSelect').value=state.user?.language||state.lang;$('profileForm')?.addEventListener('submit',saveProfile);$('avatarInput')?.addEventListener('change',uploadAvatar);$('codeForm')?.addEventListener('submit',changeOwnCode);$('refreshSessions')?.addEventListener('click',loadSessions);$('allianceForm')?.addEventListener('submit',saveAlliance);$('applicationForm')?.addEventListener('submit',saveApplication);$('openMembersButton')?.addEventListener('click',openMembers);if(state.settingsTab==='profile')loadSessions();}
async function saveProfile(e){e.preventDefault();try{hydrate(await api('/api/profile',{method:'PATCH',body:JSON.stringify({display_name:$('displayName').value.trim(),language:$('languageSelect').value})}));showMessage('profileMessage','Enregistré.')}catch(err){showMessage('profileMessage',err.message,true)}}
async function uploadAvatar(e){const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024)return showMessage('profileMessage','Fichier trop volumineux.',true);const fd=new FormData();fd.append('avatar',f);try{hydrate(await api('/api/profile/avatar',{method:'POST',body:fd}));paintAvatar($('settingsAvatar'),state.user);showMessage('profileMessage','Photo enregistrée.')}catch(err){showMessage('profileMessage',err.message,true)}e.target.value=''}
async function changeOwnCode(e){e.preventDefault();const cur=$('currentCode').value.trim(),n=$('newCode').value.trim();if(!/^\d{6}$/.test(cur)||!/^\d{6}$/.test(n))return showMessage('codeMessage','Deux codes à 6 chiffres sont requis.',true);try{await api('/api/me/code',{method:'PATCH',body:JSON.stringify({current_code:cur,new_code:n})});$('currentCode').value='';$('newCode').value='';showMessage('codeMessage','Code modifié. Les autres sessions ont été fermées.');loadSessions()}catch(err){showMessage('codeMessage',err.message,true)}}
async function loadSessions(){const el=$('sessionList');if(!el)return;try{const d=await api('/api/me/sessions');state.sessions=d.sessions||[];el.innerHTML=state.sessions.map(s=>`<div class="session-row"><div><strong>${s.current?'Session actuelle':'Session'}</strong><br><small>${esc(s.user_agent||'Appareil inconnu')}</small></div><small>${new Date(s.last_seen_at).toLocaleString(state.lang)}</small></div>`).join('')||'<span class="muted">Aucune session.</span>'}catch(err){el.innerHTML=`<span class="error-text">${esc(err.message)}</span>`}}
async function revokeOthers(){try{await api('/api/me/sessions/others',{method:'DELETE'});loadSessions()}catch(err){alert(err.message)}}
async function saveAlliance(e){e.preventDefault();try{const d=await api('/api/alliance',{method:'PATCH',body:JSON.stringify({name:$('allianceName').value.trim(),server:$('allianceServer').value.trim(),logo_url:$('allianceLogo').value.trim()||null})});state.alliance=d.alliance;renderHome();showMessage('allianceMessage','Enregistré.')}catch(err){showMessage('allianceMessage',err.message,true)}}
async function saveApplication(e){e.preventDefault();try{const d=await api('/api/portal/settings',{method:'PATCH',body:JSON.stringify({welcome_text:$('welcomeText').value.trim(),guides_title:$('guidesTitle').value.trim(),guides_url:$('guidesUrl').value.trim(),train_title:$('trainTitle').value.trim(),train_url:$('trainUrl').value.trim()})});state.portalSettings=d.portal_settings||{};renderHome();showMessage('applicationMessage','Enregistré.')}catch(err){showMessage('applicationMessage',err.message,true)}}

// Members
function openMembers(){if(!isAdmin())return;closeSettings();$('membersView').classList.remove('hidden');$('membersView').setAttribute('aria-hidden','false');state.filters.clear();state.search='';$('memberSearch').value='';renderRankFilters();loadMembers()}
function closeMembers(){$('membersView').classList.add('hidden');$('membersView').setAttribute('aria-hidden','true');openSettings('alliance')}
function renderRankFilters(){const el=$('rankFilters');const items=['ALL',...RANKS];el.innerHTML=items.map(r=>{const active=r==='ALL'?state.filters.size===0:state.filters.has(r);return `<button type="button" class="rank-filter ${active?'active':''}" data-rank="${r}" aria-pressed="${active}">${r==='ALL'?'TOUS':r}</button>`}).join('')}
$('rankFilters').addEventListener('click',e=>{const b=e.target.closest('[data-rank]');if(!b)return;const r=b.dataset.rank;if(r==='ALL')state.filters.clear();else state.filters.has(r)?state.filters.delete(r):state.filters.add(r);renderRankFilters();renderMembers()});
$('memberSearch').addEventListener('input',e=>{state.search=e.target.value||'';renderMembers()});
async function loadMembers(){try{const d=await api('/api/admin/members');state.members=d.members||[];renderMembers()}catch(err){$('memberList').innerHTML=`<div class="empty-state">${esc(err.message)}</div>`}}
function memberAvatar(m){const src=avatarUrl(m);return `<span class="member-avatar">${src?`<img src="${esc(src)}" alt="${esc(m.display_name||m.player_name||'joueur')}">`:esc(initials(m.display_name||m.player_name))}</span>`}
function relative(v){if(!v)return'jamais connecté';const ms=Date.now()-new Date(v).getTime();if(ms<120000)return'en ligne';const h=Math.floor(ms/3600000);if(h<1)return`il y a ${Math.max(1,Math.floor(ms/60000))} min`;if(h<24)return`il y a ${h} h`;const d=Math.floor(h/24);return`il y a ${d} jour${d>1?'s':''}`}
function filtered(){const q=state.search.trim().toLocaleLowerCase(state.lang);return state.members.filter(m=>(!state.filters.size||state.filters.has(m.rank))&&(!q||`${m.display_name||''} ${m.player_name||''} ${m.rank||''} ${m.officer_title||''}`.toLocaleLowerCase(state.lang).includes(q)))}
function toggleAllowed(m){return m.id!==state.user?.id&&m.rank!=='R5'&&m.system_role!=='OWNER'}
function renderMembers(){const list=filtered();$('membersCount').textContent=`${list.length} / ${state.members.length}`;$('memberList').innerHTML=list.length?list.map(m=>`<article class="member-row ${m.active?'':'inactive'}">${memberAvatar(m)}<div class="member-main"><b>${esc(m.display_name||m.player_name)}</b><div class="member-meta"><span class="rank-badge">${esc(m.rank)}</span> · ${m.active?'actif':'désactivé'}${m.officer_title?` · ${esc(OFFICE_FR[m.officer_title]||m.officer_title)}`:''}${m.system_role==='OWNER'?' · OWNER':''}</div><div class="member-last">🕒 ${esc(relative(m.last_login_at))}</div></div><div class="member-actions"><button class="small-btn edit" type="button" data-action="edit-member" data-id="${esc(m.id)}">✏️ ${esc(t('members.edit'))}</button><button class="small-btn" type="button" data-action="toggle-member" data-id="${esc(m.id)}" ${toggleAllowed(m)?'':'disabled'}>${toggleAllowed(m)?(m.active?esc(t('members.disable')):esc(t('members.enable'))):'Protégé'}</button></div></article>`).join(''):'<div class="empty-state">Aucun joueur trouvé.</div>'}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden');$('modalBody').innerHTML=''}
function rankOptions(m){return ['R4','R3','R2','R1'].map(r=>`<option value="${r}" ${m?.rank===r?'selected':''}>${r}</option>`).join('')}
function officeOptions(m){return OFFICES.map(o=>`<option value="${o}" ${m?.officer_title===o?'selected':''}>${o?(OFFICE_FR[o]||o):'Aucune'}</option>`).join('')}
function openMemberModal(id=''){const m=id?state.members.find(x=>x.id===id):null;if(!m){openModal(`<div class="modal-title"><div><p class="eyebrow">Administration</p><h3>＋ Ajouter un joueur</h3></div></div><div class="settings-form"><label class="field-label">Pseudo exact</label><input id="mName" maxlength="40"><div class="form-grid"><div><label class="field-label">Rang</label><select id="mRank">${rankOptions(null)}</select></div><div><label class="field-label">Fonction R4</label><select id="mOffice">${officeOptions(null)}</select></div></div><div id="memberModalMessage" class="hidden"></div><div class="modal-actions"><button class="primary-button" type="button" data-action="save-member">💾 Enregistrer</button><button class="secondary-button" type="button" data-action="close-modal">Annuler</button></div></div>`);$('mRank').addEventListener('change',syncOffice);syncOffice();return}const isR5=m.rank==='R5';openModal(`<div class="modal-title">${memberAvatar(m)}<div><p class="eyebrow">Administration</p><h3>${esc(m.display_name||m.player_name)}</h3></div></div><input id="mId" type="hidden" value="${esc(m.id)}"><div class="form-grid"><div><label class="field-label">Rang</label>${isR5?`<input value="R5" disabled>`:`<select id="mRank">${rankOptions(m)}</select>`}</div><div><label class="field-label">Fonction R4</label><select id="mOffice" ${isR5?'disabled':''}>${officeOptions(m)}</select></div></div><label class="toggle-row"><span>Profil actif</span><input id="mActive" type="checkbox" ${m.active?'checked':''} ${!toggleAllowed(m)?'disabled':''}></label><div id="memberModalMessage" class="hidden"></div><div class="modal-actions">${!isR5?'<button class="primary-button" type="button" data-action="save-member">💾 Enregistrer</button>':''}<button class="secondary-button" type="button" data-action="reset-member-code" data-id="${esc(m.id)}">🔑 Nouveau code</button>${m.rank==='R4'?`<button class="secondary-button" type="button" data-action="transfer-r5" data-id="${esc(m.id)}">♛ Nommer R5</button>`:''}<button class="secondary-button" type="button" data-action="close-modal">Fermer</button></div>`);if($('mRank')){$('mRank').addEventListener('change',syncOffice);syncOffice()}}
function syncOffice(){const r=$('mRank'),o=$('mOffice');if(!o||!r)return;o.disabled=r.value!=='R4';if(o.disabled)o.value=''}
function randomCode(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(a[0]%1000000).padStart(6,'0')}
async function saveMember(){const id=$('mId')?.value||'';if(!id){const name=$('mName').value.trim(),rank=$('mRank').value,off=rank==='R4'?($('mOffice').value||null):null;if(!name)return showMessage('memberModalMessage','Pseudo obligatoire.',true);let last;for(let i=0;i<8;i++){const code=randomCode();try{await api('/api/admin/members',{method:'POST',body:JSON.stringify({player_name:name,rank,officer_title:off,code})});await loadMembers();openModal(`<p class="eyebrow">Joueur ajouté</p><h3>${esc(name)}</h3><p>Code personnel :</p><div class="new-code">${code}</div><p class="muted">Copiez ce code avant de fermer.</p><div class="modal-actions"><button class="primary-button" data-action="copy-code" data-code="${code}">📋 Copier</button><button class="secondary-button" data-action="close-modal">Fermer</button></div>`);return}catch(e){last=e;if(!/CODE|EXISTS/i.test(e.message))break}}return showMessage('memberModalMessage',last?.message||'Erreur',true)}const m=state.members.find(x=>x.id===id);if(!m)return;const rank=$('mRank')?.value||m.rank,off=rank==='R4'?($('mOffice')?.value||null):null,active=$('mActive')?.checked??m.active;try{if(m.officer_title&&rank!=='R4')await api(`/api/admin/members/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({officer_title:null})});if(rank!==m.rank)await api(`/api/admin/members/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({rank})});if(rank==='R4'&&off!==(m.officer_title||null))await api(`/api/admin/members/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({officer_title:off})});if(Boolean(active)!==Boolean(m.active))await api(`/api/admin/members/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({active:Boolean(active)})});await loadMembers();closeModal()}catch(e){showMessage('memberModalMessage',e.message,true)}}
async function toggleMember(id){const m=state.members.find(x=>x.id===id);if(!m||!toggleAllowed(m))return;try{await api(`/api/admin/members/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({active:!m.active})});await loadMembers()}catch(e){alert(e.message)}}
async function resetMemberCode(id){const code=randomCode();try{await api(`/api/admin/members/${encodeURIComponent(id)}/code`,{method:'POST',body:JSON.stringify({code})});openModal(`<p class="eyebrow">Nouveau code</p><div class="new-code">${code}</div><p class="muted">Les anciennes sessions de ce joueur ont été fermées.</p><div class="modal-actions"><button class="primary-button" data-action="copy-code" data-code="${code}">📋 Copier</button><button class="secondary-button" data-action="close-modal">Fermer</button></div>`)}catch(e){showMessage('memberModalMessage',e.message,true)}}
function openTransfer(id){const m=state.members.find(x=>x.id===id);if(!m)return;openModal(`<p class="eyebrow">Leadership</p><h3>♛ Nommer ${esc(m.display_name||m.player_name)} R5</h3><p class="muted">Le R5 actuel sera rétrogradé R4. Confirme avec ton propre code à 6 chiffres.</p><input id="transferCode" type="password" inputmode="numeric" maxlength="6" placeholder="••••••"><div id="memberModalMessage" class="hidden"></div><div class="modal-actions"><button class="primary-button" data-action="confirm-transfer" data-id="${esc(id)}">Confirmer</button><button class="secondary-button" data-action="close-modal">Annuler</button></div>`)}
async function confirmTransfer(id){const code=$('transferCode').value.trim();if(!/^\d{6}$/.test(code))return showMessage('memberModalMessage','Code à 6 chiffres requis.',true);try{await api('/api/admin/leadership/transfer',{method:'POST',body:JSON.stringify({target_user_id:id,current_code:code})});await loadMembers();closeModal()}catch(e){showMessage('memberModalMessage',e.message,true)}}
async function copyText(text,btn){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}if(btn)btn.textContent='✅ Copié'}

boot();
})();
