from pathlib import Path

p=Path('.github/qa/train-recette-extended.mjs')
s=p.read_text(encoding='utf-8')
old="""  await test('Mobile : modale profil utilisable et scrollable sans sortir de l’écran',async()=>{\n    const s=await session(browser,'R4',{viewport:{width:360,height:640},isMobile:true,hasTouch:true});await s.page.evaluate(()=>window.W.openSelfProfileEdit());const box=await s.page.locator('#modal .modal-sheet').boundingBox();assert.ok(box);assert.ok(box.width<=360);const style=await s.page.locator('#modal .modal-sheet').evaluate(el=>({sh:el.scrollHeight,ch:el.clientHeight,oy:getComputedStyle(el).overflowY}));assert.ok(style.ch<=640);assert.deepEqual(s.errors,[]);await s.context.close();\n  });"""
new="""  await test('Mobile : modale profil utilisable et scrollable sans sortir de l’écran',async()=>{\n    const s=await session(browser,'R4',{viewport:{width:360,height:640},isMobile:true,hasTouch:true});\n    await s.page.evaluate(()=>window.W.openSelfProfileEdit());\n    await s.page.locator('#selfPseudoField').waitFor({state:'visible',timeout:5000});\n    const metrics=await s.page.evaluate(()=>{\n      const modal=document.getElementById('modal'),field=document.getElementById('selfPseudoField');\n      if(!modal||!field)return null;\n      let panel=field.parentElement;\n      while(panel&&panel.parentElement&&panel.parentElement!==modal)panel=panel.parentElement;\n      panel=panel||modal;\n      const r=panel.getBoundingClientRect(),cs=getComputedStyle(panel);\n      return {hidden:modal.classList.contains('hidden'),left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,sh:panel.scrollHeight,ch:panel.clientHeight,oy:cs.overflowY};\n    });\n    assert.ok(metrics);assert.equal(metrics.hidden,false);\n    assert.ok(metrics.left>=-2&&metrics.right<=362,`horizontal ${metrics.left}/${metrics.right}`);\n    assert.ok(metrics.width<=362,`width ${metrics.width}`);\n    assert.ok(metrics.top>=-2&&metrics.bottom<=642,`vertical ${metrics.top}/${metrics.bottom}`);\n    assert.ok(metrics.sh<=metrics.ch+1||['auto','scroll'].includes(metrics.oy),`not scrollable sh=${metrics.sh} ch=${metrics.ch} oy=${metrics.oy}`);\n    assert.deepEqual(s.errors,[]);await s.context.close();\n  });"""
if old not in s:
    raise SystemExit('mobile modal test block not found')
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('MOBILE_MODAL_RECETTE_FIX=OK')
