from pathlib import Path

path = Path('frontend/_worker.js')
src = path.read_text(encoding='utf-8')

old_css = """      style.textContent='@keyframes wfggTrainRide{0%{transform:translateX(-72px)}100%{transform:translateX(292px)}}@keyframes wfggTrainPulse{0%,100%{opacity:.55}50%{opacity:1}}#wfggTrainPortalGate .wfgg-train-stage{position:relative;width:min(320px,78vw);height:76px;overflow:hidden}#wfggTrainPortalGate .wfgg-train-track{position:absolute;left:0;right:0;bottom:18px;height:2px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.58) 12%,rgba(255,255,255,.58) 88%,transparent)}#wfggTrainPortalGate .wfgg-train-track:after{content:\"\";position:absolute;left:10%;right:10%;top:7px;height:2px;background:repeating-linear-gradient(90deg,rgba(255,255,255,.28) 0 8px,transparent 8px 18px)}#wfggTrainPortalGate .wfgg-train-sprite{position:absolute;left:0;bottom:24px;font-size:38px;line-height:1;filter:drop-shadow(0 4px 10px rgba(0,0,0,.45));animation:wfggTrainRide 1.9s cubic-bezier(.45,.05,.55,.95) infinite}#wfggTrainPortalGate .wfgg-train-light{position:absolute;left:50%;bottom:3px;width:7px;height:7px;border-radius:50%;background:rgba(255,255,255,.72);animation:wfggTrainPulse 1.15s ease-in-out infinite}@media (prefers-reduced-motion:reduce){#wfggTrainPortalGate .wfgg-train-sprite{animation-duration:4s}}';
"""

new_css = """      style.textContent='@keyframes wfggTrainRide{0%{transform:translateX(-180px)}100%{transform:translateX(370px)}}@keyframes wfggWheelSpin{to{transform:rotate(360deg)}}#wfggTrainPortalGate .wfgg-train-stage{position:relative;width:min(340px,82vw);height:92px;overflow:hidden}#wfggTrainPortalGate .wfgg-train-track{position:absolute;left:0;right:0;bottom:17px;height:3px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.65) 10%,rgba(255,255,255,.65) 90%,transparent)}#wfggTrainPortalGate .wfgg-train-track:after{content:\"\";position:absolute;left:8%;right:8%;top:8px;height:3px;background:repeating-linear-gradient(90deg,rgba(255,255,255,.28) 0 10px,transparent 10px 22px)}#wfggTrainPortalGate .wfgg-train-sprite{position:absolute;left:0;bottom:26px;width:154px;height:50px;filter:drop-shadow(0 5px 10px rgba(0,0,0,.48));animation:wfggTrainRide 2.15s linear infinite}#wfggTrainPortalGate .wfgg-train-engine,#wfggTrainPortalGate .wfgg-train-car{position:absolute;bottom:9px;height:30px;background:linear-gradient(180deg,#eeeeF2,#a8aab4);border:2px solid rgba(255,255,255,.8);box-sizing:border-box}#wfggTrainPortalGate .wfgg-train-engine{right:0;width:72px;border-radius:7px 17px 5px 5px}#wfggTrainPortalGate .wfgg-train-engine:after{content:\"\";position:absolute;right:-8px;bottom:-2px;border-left:9px solid #a8aab4;border-top:13px solid transparent}#wfggTrainPortalGate .wfgg-train-car{left:0;width:74px;border-radius:7px 5px 5px 5px}#wfggTrainPortalGate .wfgg-train-coupler{position:absolute;left:72px;bottom:21px;width:11px;height:3px;background:#d9dae2}#wfggTrainPortalGate .wfgg-train-window{position:absolute;top:6px;width:12px;height:10px;border-radius:2px;background:#232839;box-shadow:inset 0 0 0 1px rgba(255,255,255,.18)}#wfggTrainPortalGate .wfgg-train-car .wfgg-train-window:nth-child(1){left:9px}#wfggTrainPortalGate .wfgg-train-car .wfgg-train-window:nth-child(2){left:29px}#wfggTrainPortalGate .wfgg-train-car .wfgg-train-window:nth-child(3){left:49px}#wfggTrainPortalGate .wfgg-train-engine .wfgg-train-window{right:14px;width:19px;transform:skewX(-12deg)}#wfggTrainPortalGate .wfgg-train-wheel{position:absolute;bottom:1px;width:14px;height:14px;border-radius:50%;background:#14151d;border:3px solid #747784;box-sizing:border-box;animation:wfggWheelSpin .45s linear infinite}#wfggTrainPortalGate .wfgg-wheel-a{left:14px}#wfggTrainPortalGate .wfgg-wheel-b{left:50px}#wfggTrainPortalGate .wfgg-wheel-c{left:95px}#wfggTrainPortalGate .wfgg-wheel-d{left:132px}@media (prefers-reduced-motion:reduce){#wfggTrainPortalGate .wfgg-train-sprite{animation-duration:5s}#wfggTrainPortalGate .wfgg-train-wheel{animation:none}}';
"""

old_html = """      el.innerHTML='<div class=\"wfgg-train-stage\" aria-hidden=\"true\"><div class=\"wfgg-train-track\"></div><div class=\"wfgg-train-sprite\">🚆</div><div class=\"wfgg-train-light\"></div></div>';
"""

new_html = """      el.innerHTML='<div class=\"wfgg-train-stage\" aria-hidden=\"true\"><div class=\"wfgg-train-track\"></div><div class=\"wfgg-train-sprite\"><div class=\"wfgg-train-car\"><span class=\"wfgg-train-window\"></span><span class=\"wfgg-train-window\"></span><span class=\"wfgg-train-window\"></span></div><div class=\"wfgg-train-coupler\"></div><div class=\"wfgg-train-engine\"><span class=\"wfgg-train-window\"></span></div><span class=\"wfgg-train-wheel wfgg-wheel-a\"></span><span class=\"wfgg-train-wheel wfgg-wheel-b\"></span><span class=\"wfgg-train-wheel wfgg-wheel-c\"></span><span class=\"wfgg-train-wheel wfgg-wheel-d\"></span></div></div>';
"""

if old_css not in src:
    raise SystemExit('Expected Train animation CSS not found')
if old_html not in src:
    raise SystemExit('Expected Train animation HTML not found')

src = src.replace(old_css, new_css, 1)
src = src.replace(old_html, new_html, 1)
path.write_text(src, encoding='utf-8')
